### ISSUE TITLE
Feilmelding ved `nais start`

### ISSUE THREAD

**Issue by almyy** [nais/cli#385]
Får følgende feilmelding når jeg kjører `nais start teamdigisos sosialhjelp-avtaler-admin`

OS: Ubuntu 22.04, Regolith

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x137f318]

goroutine 1 [running]:
github.com/nais/cli/pkg/appstarter.makeHttpRequest(0x0?)
	/home/runner/work/cli/cli/pkg/appstarter/appstarter.go:122 +0x2d8
github.com/nais/cli/pkg/appstarter.Naisify({0x7fff620b9fd2, 0x19}, {0x7fff620b9fc6, 0xb}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...)
	/home/runner/work/cli/cli/pkg/appstarter/appstarter.go:60 +0x278
github.com/nais/cli/cmd.commands.Command.func2(0xc0001fe6c0)
	/home/runner/work/cli/cli/cmd/appstartercmd/appstarter.go:47 +0x132
github.com/urfave/cli/v2.(*Command).Run(0xc00035cf20, 0xc0001fe6c0, {0xc0007150b0, 0x3, 0x3})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x97d
github.com/urfave/cli/v2.(*Command).Run(0xc0003b91e0, 0xc0001fe540, {0xc000148040, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:272 +0xbb7
github.com/urfave/cli/v2.(*App).RunContext(0xc0003ba000, {0x2083b30, 0x2fbb300}, {0xc000148040, 0x4, 0x4})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x58b
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
github.com/nais/cli/cmd.Run()
	/home/runner/work/cli/cli/cmd/cmd.go:47 +0x14c
main.main()
	/home/runner/work/cli/cli/main.go:6 +0xf
```

**Comment by ybelMekk** [comment]
Denne er fjernet nå, ettersom det kommer en bedre lösning for dette
